language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget https://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz
  - tar xf arduino-1.8.4-linux64.tar.xz
  - sudo mv arduino-1.8.4 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - cp -r `find libraries/ -type f` controller_sensormod
  - cp -r `find libraries/ -type f` controller_base
install:
  - arduino --install-library "Time"
  - arduino --install-library "SD"
script:
  - arduino --verify --board arduino:avr:uno controller_sensormod/controller_sensormod.ino
  - arduino --verify --board arduino:avr:uno controller_base/controller_base.ino
